### ISSUE TITLE
Please check Xenia project for these High Errors

### ISSUE THREAD

**Issue by drillsar** [viva64/pvs-studio-check-list#129]
The following errors please check to see if it's false or indeed an errors.

Xenia Project:
https://github.com/benvanik/xenia

V570 The 'constant.i8' variable is assigned to itself. value.cc 1372
V547 Expression 'v' is always false. ppc_emit_control.cc 449
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: irql_. processor.cc 80
V512 A call of the 'memcpy' function will lead to overflow of the buffer '& thread_context.Rax'. stack_walker_win.cc 179
V512 A call of the 'memcpy' function will lead to overflow of the buffer '& thread_context.Xmm0'. stack_walker_win.cc 181
V512 A call of the 'memcpy' function will lead to the '& thread_context.Rax' buffer becoming out of range. stack_walker_win.cc 189
V512 A call of the 'memcpy' function will lead to the '& thread_context.Xmm0' buffer becoming out of range. stack_walker_win.cc 191
V569 Truncation of constant value 3735929054. The value range of unsigned char type: [0, 255]. xex_module.cc 393
V569 Truncation of constant value 4027445261. The value range of unsigned char type: [0, 255]. xex_module.cc 409
V792 The 'isREG' function located to the right of the operator '|' will be called regardless of the value of the left operand. Perhaps, it is better to use '||'. xbyak.h 409
V792 The 'isExtIdx' function located to the right of the operator '|' will be called regardless of the value of the left operand. Perhaps, it is better to use '||'. xbyak.h 409
V690 The 'Pack' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class. xbyak_util.h 309
V647 The value of 'int' type is assigned to the pointer of 'int' type. pthread_frame.c 265
V647 The value of 'int' type is assigned to the pointer of 'enum' type. utils.c 947
V570 The 'collected_size_bits' variable is assigned to itself. xma2dec.c 1791
V647 The value of 'int' type is assigned to the pointer of 'char' type. Consider inspecting the assignment: 'm->elems[m->count].key = av_strdup(key)'. dict.c 107
V647 The value of 'int' type is assigned to the pointer of 'char' type. Consider inspecting the assignment: 'oldval = av_realloc(oldval, len)'. dict.c 112
V647 The value of 'int' type is assigned to the pointer of 'char' type. dict.c 117
V647 The value of 'int' type is assigned to the pointer of 'unsigned char' type. Consider inspecting the assignment: '= av_realloc(NULL, size)'. buffer.c 155
V647 The value of 'int' type is assigned to the pointer of 'unsigned char' type. buffer.c 188

<Clipboard contents were truncated. A valid license is required for copying a full version of analysis log.>

**Comment by Vkhanieva** [comment]
Added project to check list, commit 39c3438495c4f6519d5ee0f7bc9d1dea492a92c8
