### ISSUE TITLE
Project to check opensource Counter-Strike 1.6 addon

### ISSUE THREAD

**Issue by AngeIII** [viva64/pvs-studio-check-list#15]
A long time ago we all was played counter-strike, and there is a big addon named AmxModx created by alliedmodders was used for millions of counter-strike servers. may you check it?

It is still alive, it is interesting and it is written in c/c++

@arkshine

https://github.com/alliedmodders/amxmodx/

**Comment by SvyatoslavRazmyslov** [comment]
ffc4ff6f4cdd45b21dc728e4890a525874ed29d0
