### ISSUE TITLE
Check DXVK, open source D3D11 to Vulkan translation layer

### ISSUE THREAD

**Issue by tannisroot** [viva64/pvs-studio-check-list#182]
DXVK is a C++/C project aimed at translating D3D11 (DirectX11) calls to Vulkan. It was picked up by Valve for their new SteamPlay/Proton project that brings Windows games to Linux.
Github: https://github.com/doitsujin/dxvk
License: Zlib

**Comment by Vkhanieva** [comment]
https://github.com/viva64/pvs-studio-check-list/commit/76981c2acf761931aba1e51200e96aeca13adf34
