### ISSUE TITLE
GDAL - Geospatial Data Abstraction Library

### ISSUE THREAD

**Issue by mloskot** [viva64/pvs-studio-check-list#67]
GDAL is a translator library for raster and vector geospatial data formats. It also comes with a variety of useful command line utilities for data translation and processing as well as APIs for popular languages (eg. Python, Perl, .NET). Functional and integration test suite is developed in Python.

Website: http://gdal.org

Source code packages: https://trac.osgeo.org/gdal/wiki/DownloadSource

Source code repository:
* Subversion: https://svn.osgeo.org/gdal
* Git mirror (active):  https://github.com/OSGeo/gdal

License: MIT

/cc @rouault

**Comment by Vkhanieva** [comment]
Added project to check list, commit 8fb2117db0adb4a1700e0474205f5ae6a26efc2e

**Comment by mloskot** [comment]
@Vkhanieva Thank you! Could you tell when and where some reports could be expected?
