### ISSUE TITLE
GEOS - Geometry Engine, Open Source

### ISSUE THREAD

**Issue by mloskot** [viva64/pvs-studio-check-list#68]
GEOS is a C++ port of the ​Java Topology Suite (JTS). This includes all the ​OpenGIS Simple Features for SQL spatial predicate functions and spatial operators, as well as specific JTS enhanced topology functions. 

Website: https://trac.osgeo.org/geos/

Latest release source code package: http://download.osgeo.org/geos/geos-3.6.1.tar.bz2

Source code repository:

    Subversion: https://svn.osgeo.org/geos
    Git mirror (active): https://github.com/libgeos/libgeos

License: LGPL

/cc @strk

**Comment by Vkhanieva** [comment]
Added project to check list, commit 8fb2117db0adb4a1700e0474205f5ae6a26efc2e

**Comment by mloskot** [comment]
@Vkhanieva Thank you! Could you tell when and where some reports could be expected?
