### ISSUE TITLE
Не умею работать с гит, предложу на проверку 

### ISSUE THREAD

**Issue by Radzhab** [viva64/pvs-studio-check-list#9]
https://github.com/CrowdStrike/Tortilla

**Comment by magicgoose** [comment]
для этого не обязательно уметь работать с гит, можно тупо прямо через браузер сделать пулл реквест.

**Comment by Radzhab** [comment]
Не могли бы вы помочь мне с этим делом

**Comment by magicgoose** [comment]
![screen shot 2017-02-08 at 21 11 37-or8](https://cloud.githubusercontent.com/assets/1442206/22753044/5fa6fe0e-ee43-11e6-9132-51f12c94a197.png)

**Comment by SvyatoslavRazmyslov** [comment]
@Radzhab Это очень маленький проект для статьи, но Вы можете [бесплатно](http://www.viva64.com/ru/b/0457/) проверить его сами.
